# #####################################################################################
#
# SYSTEM - Audio
#
# #####################################################################################
# System - Main Audio Selector
# ##################################
# - alias: system_main_audio_selector
#   initial_state: false
#   trigger:
#     - platform: state
#       entity_id: input_select.main_audio_out
#   condition:
#     - condition: template
#       value_template: >
#         {% set ignore = ['unknown', 'unavailable', 'none'] %}
#         {{ trigger.from_state.state not in ignore and
#           trigger.to_state.state not in ignore and
#           trigger.to_state.state != trigger.from_state.state }}  
#   action:
#     - service: input_boolean.set_value
#       data:
#         entity_id: input_text.bedroom
#         value: >
#           {% if is_state("input_select.main_audio_out", "Kitchen GHM") %} media_player.home_mini_k
#           {% elif is_state("input_select.main_audio_out", "Vova's room GHM") %} media_player.home_mini_v
#           {% elif is_state("input_select.main_audio_out", "Sasha's room GHM") %} media_player.home_mini_s
#           {% elif is_state("input_select.main_audio_out", "Master Bedroom GHM ") %} media_player.home_mini_mb
#           {% elif is_state("input_select.main_audio_out", "MPD") %} media_player.mpd
#           {% elif is_state("input_select.main_audio_out", "Hall big GHM") %} media_player.home_mini_hb
#           {% elif is_state("input_select.main_audio_out", "Everywhere") %} media_player.all_speakers
#           {% elif is_state("input_select.main_audio_out", "Minis") %} media_player.google_home_minis
#           {% endif %}

# ##################################
# System - Radio Volume
# ##################################
- alias: system_set_radio_volume
  #id:system_set_radio_volume
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_number.volume_radio
  action:
    - service: media_player.volume_set
      data:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Kitchen") %} media_player.yandex_lite_k
          {% elif is_state("input_select.chromecast_radio", "Vova's room") %} media_player.yandex_lite_v
          {% elif is_state("input_select.chromecast_radio", "Sasha's room") %} media_player.yandex_lite_s
          {% elif is_state("input_select.chromecast_radio", "Master Bedroom") %} media_player.yandex_lite_mb
          {% elif is_state("input_select.chromecast_radio", "MPD") %} media_player.mpd
          {% elif is_state("input_select.chromecast_radio", "Hall big") %} media_player.yandex_lite_hb
          {% endif %}
        volume_level: "{{ states('input_number.volume_radio') }}"

# ##################################
# System - TTS from telegram
# ##################################
# - alias: system_tts_from_teleram
#   #id: system_tts_from_telegram
#   initial_state: true
#   trigger:
#     - platform: event
#       event_type: telegram_command
#       event_data:
#         command: /tts
#   action:
#     - delay:
#         seconds: 5
#     - service: tts.yandextts_say
#       entity_id: media_player.mpd
#       data:
#         message: '{% for state in trigger.event.data["args"] %}{{ state }} {% endfor %}'