# #####################################################################################
#
# SYSTEM - Snapshot
#
# #####################################################################################
# System - Window Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_window
  id: system_snapshot_window
  initial_state: true
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.g5_bullet_window_motion
      from: "off"
      to: "on"
  conditions:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_window', 'last_triggered'),0)|int(0)) > 10 }}"
  actions:
      - action: telegram_bot.send_photo
        data:
          url: http://localhost:1984/api/frame.jpeg?src=g5_window #!secret window_snap
          caption: "\U0001f4f7 Window {{states('sensor.time')}} {{states('sensor.date')}}"
          target: !secret tel_chat_id_cam
          timeout: 180

    # - action: notify.send_message
    #   data:
    #     entity_id: notify.telegram_cam
    #     message: "Window"
    #     data:
    #       photo:
    #         - url: http://localhost:1984/api/frame.jpeg?src=g5_window #!secret street_snap
    #           caption: "\U0001f4f7 Window {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Yard Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_yard
  id: system_snapshot_yard
  initial_state: true
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.g5_bullet_yard_motion
      from: "off"
      to: "on"
  conditions:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_yard', 'last_triggered'),0)|int(0)) > 10 }}"
  actions:
      - action: telegram_bot.send_photo
        data:
          url: http://localhost:1984/api/frame.jpeg?src=g5_yard #!secret yard_snap
          caption: "\U0001f4f7 Yard {{states('sensor.time')}} {{states('sensor.date')}}"
          target: !secret tel_chat_id_cam
          timeout: 180
    # - action: notify.send_message
    #   data:
    #     entity_id: notify.telegram_cam
    #     #title: "Send an images"
    #     message: "Yard"
    #     data:
    #       photo:
    #         - url: http://localhost:1984/api/frame.jpeg?src=g5_yard #!secret street_snap
    #           caption: "\U0001f4f7 Yard {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Dixy Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_dixy
  id: system_snapshot_dixy
  initial_state: true
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.g5_turret_dixy_motion
      from: "off"
      to: "on"
  conditions:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_dixy', 'last_triggered'),0)|int(0)) > 10 }}"
  actions:
      - action: telegram_bot.send_photo
        data:
          url: http://localhost:1984/api/frame.jpeg?src=g5_dixy #!secret dixy_snap
          caption: "\U0001f4f7 Dixy {{states('sensor.time')}} {{states('sensor.date')}}"
          target: !secret tel_chat_id_cam
          timeout: 180
    # - action: notify.send_message
    #   data:
    #     entity_id: notify.telegram_cam
    #     #title: "Send an images"
    #     message: "Dixy"
    #     data:
    #       photo:
    #         - url: http://localhost:1984/api/frame.jpeg?src=g5_dixy #!secret street_snap
    #           caption: "\U0001f4f7 Dixy {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Street Cam Snapshot on Motion
# ##################################
- alias: system_snapshot_street
  id: system_snapshot_street
  initial_state: true
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.g5_turret_street_motion
      from: "off"
      to: "on"
  conditions:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snapshot_street', 'last_triggered'),0)|int(0)) > 10 }}"
  actions:
      - action: telegram_bot.send_photo
        data:
          url: http://localhost:1984/api/frame.jpeg?src=g5_street #!secret street_snap
          caption: "\U0001f4f7 Street {{states('sensor.time')}} {{states('sensor.date')}}"
          target: !secret tel_chat_id_cam
          timeout: 180
    # - action: notify.send_message
    #   data:
    #     entity_id: notify.telegram_cam
    #     #title: "Send an images"
    #     message: "Street"
    #     data:
    #       photo:
    #         - url: http://localhost:1984/api/frame.jpeg?src=g5_street #!secret street_snap
    #           caption: "\U0001f4f7 Street {{states('sensor.time')}} {{states('sensor.date')}}"

# ##################################
# System - Motion Outside
# ##################################
- alias: system_snaphot_outside
  id: system_snaphot_outside
  initial_state: true
  mode: single
  max_exceeded: silent
  triggers:
    - trigger: state
      entity_id: binary_sensor.g4_doorbell_motion
      from: "off"
      to: "on"
  conditions:
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.system_snaphot_outside', 'last_triggered'),0)|int(0)) > 15 }}"
  actions:
      - action: telegram_bot.send_photo
        data:
          url: http://localhost:1984/api/frame.jpeg?src=g4_doorbell #!secret doorbell_snap
          caption: "\U0001f4f7 Outside {{states('sensor.time')}} {{states('sensor.date')}}"
          target: !secret tel_chat_id_cam
          timeout: 180
    # - action: notify.send_message
    #   data:
    #     entity_id: notify.telegram_cam
    #     #title: "Send an images"
    #     message: "Doorbell"
    #     data:
    #       photo:
    #         - url: http://localhost:1984/api/frame.jpeg?src=g4_doorbell #!secret street_snap
    #           caption: "\U0001f4f7 Doorbell {{states('sensor.time')}} {{states('sensor.date')}}"
