# #####################################################################################
#
# System - Lights
#
# #####################################################################################
# System - Single person at home light control
# ##################################
- alias: system_single_person_at_home_light_control
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: 
        - light.square_led_v
        - light.round_led_k
        - light.round_led_mb
        - light.round_led_s
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ states('sensor.people_home')|int == 1 }}"
  action:
    - service: light.turn_off
      data_template:
        entity_id: > 
          {{states.light | map(attribute='entity_id') | select('ne',trigger.entity_id) | join(', ') }}

# ##################################
# System - Circadian lightning toggle room
# ##################################
- alias: system_circadian_toggle
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id:
        - switch.circadian_lighting_k
        - switch.circadian_lighting_s
        - switch.circadian_lighting_v
        - switch.circadian_lighting_mb
      from: 'on'
      to: 'off'
  condition: 
    - condition: state
      entity_id: switch.circadian_lighting_all
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_all