# #####################################################################################
#
# VOVA - Lights
#
# #####################################################################################
# Vova- Breazer On
# ################################## 
- alias: vova_breazer_on
  initial_state: "false"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: binary_sensor.family_home
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.z19_co2_v
      above: 1000
    - condition: state
      entity_id: binary_sensor.breather_v
      state: 'off'
    - condition: state
      entity_id: binary_sensor.0x158d00022ccffe_contact
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.digma_ir_v_breather_pwr
      
# ##################################
# Vova - Breazer Off
# ################################## 
- alias: vova_breazer_off
  initial_state: "false"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.z19_co2_v
          below: 800
        - condition: state
          entity_id: binary_sensor.breather_v
          state: 'on'
      - condition: and
        conditions:
        - condition: state
          entity_id: binary_sensor.0x158d00022ccffe_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.breather_v
          state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.digma_ir_v_breather_pwr
