background: var(--background-image)

title: Home - Main Server - Auto Dashboard
views:

  - title: Main
    icon: mdi:home
    cards:
      - type: custom:mushroom-select-card
        entity: input_select.room_selector
        fill_container: false 
        layout: horizontal 
        secondary_info: none
      - type: conditional
        conditions:
          - condition: state
            entity: input_select.room_selector
            state: Кухня
        card:
          type: vertical-stack
          cards:
            - type: custom:mushroom-title-card
              title: Кухня
            - type: custom:mushroom-chips-card
              chips:
                - type: entity
                  entity: binary_sensor.motion_k
                  content_info: none
                  icon_color: amber
                - type: entity
                  entity: binary_sensor.0x00158d00025371f6_contact
                  use_entity_picture: false
                  icon_color: amber
                  content_info: state
                - type: entity
                  entity: sensor.0x00158d0001e586af_temperature
                  icon_color: teal
                - type: entity
                  entity: sensor.0x00158d0001e586af_humidity
                  name: Humidity K
                  icon_color: light-blue
                - type: template
                  entity: sensor.esp32_node_k_co2
                  icon_color: >-
                    {% if states('sensor.esp32_node_k_co2')|int(0) <= 700 %} green {% elif 700
                    < states('sensor.esp32_node_k_co2')|int(0) <= 1200 %} orange {% else %}
                    red {% endif %}
                  content: '{{states(''sensor.esp32_node_k_co2'')|int(0)}} ppm'
                  icon: mdi:molecule-co2
              alignment: center
            - type: custom:mushroom-chips-card
              chips:
                - type: light
                  entity: light.round_led_k
                  tap_action:
                    action: toggle
                  use_light_color: true
                  double_tap_action:
                    action: call-service
                    service: light.turn_on
                    target:
                      entity_id: light.round_led_k
                    data:
                      brightness: 255
                  name: Люстра
                  content_info: name
                - type: light
                  entity: light.esp8266_hood_k
                  tap_action:
                    action: toggle
                  use_light_color: true
                  name: Плита
                  content_info: name
                - type: light
                  entity: light.d1mini_light_l
                  tap_action:
                    action: toggle
                  use_light_color: true
                  name: Левая
                  content_info: name
                - type: light
                  entity: light.sonoff_mini_4
                  tap_action:
                    action: toggle
                  use_light_color: true
                  name: Правая
                  content_info: name
                - type: light
                  entity: light.esp32_node_k_light
                  use_light_color: true
                  name: Ночник
                  content_info: name
                - type: entity
                  entity: fan.esp8266_hood_k_fan
                  tap_action:
                    action: toggle
                  use_entity_picture: true
                  icon_color: primary
                  name: Вытяжка
                  content_info: name
              alignment: center