"""Constants for mosenergosbyt integration"""

DOMAIN = "mosenergosbyt"

ATTRIBUTION = "Data provided by Mosenergosbyt"

ATTR_ACCOUNT_CODE = "account_code"
ATTR_ADDRESS = "address"
ATTR_BENEFITS = "benefits"
ATTR_CALL_PARAMS = "call_params"
ATTR_CHARGED = "charged"
ATTR_COMMENT = "comment"
ATTR_CORRECT = "correct"
ATTR_COST = "cost"
ATTR_DESCRIPTION = "description"
ATTR_FMT_LAST_VALUE = "last_value_%s"
ATTR_FMT_SUBMITTED_VALUE = "submitted_value_%s"
ATTR_FMT_TODAY_VALUE = "today_value_%s"
ATTR_IGNORE_INDICATIONS = "ignore_indications"
ATTR_IGNORE_PERIOD = "ignore_period"
ATTR_INCREMENTAL = "incremental"
ATTR_INDICATIONS = "indications"
ATTR_INDICATIONS_DICT = "indications_dict"
ATTR_INITIAL = "initial"
ATTR_INSTALL_DATE = "install_date"
ATTR_INSURANCE = "insurance"
ATTR_INVOICE_ID = "invoice_id"
ATTR_LAST_PAYMENT_AMOUNT = "last_payment_amount"
ATTR_LAST_PAYMENT_DATE = "last_payment_date"
ATTR_LAST_PAYMENT_STATUS = "last_payment_status"
ATTR_LAST_SUBMIT_DATE = "last_submit_date"
ATTR_METER_CODE = "meter_code"
ATTR_MODEL = "model"
ATTR_NOTIFICATION = "notification"
ATTR_PAID = "paid"
ATTR_PENALTY = "penalty"
ATTR_PERIOD = "period"
ATTR_PROVIDER_NAME = "provider_name"
ATTR_REASON = "reason"
ATTR_REMAINING_DAYS = "remaining_days"
ATTR_SERVICE_NAME = "service_name"
ATTR_SERVICE_TYPE = "service_type"
ATTR_STATUS = "status"
ATTR_SUBMIT_PERIOD_ACTIVE = "submit_period_active"
ATTR_SUBMIT_PERIOD_END = "submit_period_end"
ATTR_SUBMIT_PERIOD_START = "submit_period_start"
ATTR_SUCCESS = "success"
ATTR_TOTAL = "total"
ATTR_UNIT = "unit"

CONF_ACCOUNTS = "accounts"
CONF_FILTER = "filter"
CONF_INVOICES = "invoices"
CONF_METERS = "meters"
CONF_NAME_FORMAT = "name_format"
CONF_USER_AGENT = "user_agent"

DATA_API_OBJECTS = DOMAIN + "_api_objects"
DATA_ENTITIES = DOMAIN + "_entities"
DATA_FINAL_CONFIG = DOMAIN + "_final_config"
DATA_UPDATERS = DOMAIN + "_updaters"
DATA_UPDATE_LISTENERS = DOMAIN + '_update_listeners'
DATA_YAML_CONFIG = DOMAIN + "_yaml_config"

DEFAULT_NAME_FORMAT_ACCOUNTS = "MES Account {code}"
DEFAULT_NAME_FORMAT_INVOICES = "MES Invoice {code}"
DEFAULT_MAX_INDICATIONS = 3
DEFAULT_NAME_FORMAT_METERS = "MES Meter {code}"
DEFAULT_SCAN_INTERVAL = 60 * 60  # 1 hour
