# #####################################################################################
#
# KITCHEN - Lights
#
# #####################################################################################
# Kitchen Table Lamp (Yeelight E27 Color) On
# ##################################
- alias: kitchen_table_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0001ef61be
    #     click_type: single
    - platform: state
      entity_id: sensor.0x158d0001ef61be_action
      to: 'single'
  condition:
    - condition: state
      entity_id: light.led_color_k
      state: 'off'    
  action:
    - service: light.turn_on
      entity_id: light.led_color_k
      data_template:
        brightness_pct: 100
        kelvin: 5000
      
# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) Off
# ##################################
- alias: kitchen_table_lamp_off_if_lamp_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0001ef61be
    #     click_type: single
    - platform: state
      entity_id: sensor.0x158d0001ef61be_action
      to: 'single'
  condition:
    - condition: state
      entity_id: light.led_color_k
      state: 'on'    
  action:
    - service: light.turn_off
      entity_id: light.led_color_k

# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) to bright
# ##################################
- alias: kitchen_table_lamp_to_bright
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0001ef61be
    #     click_type: double
    - platform: state
      entity_id: sensor.0x158d0001ef61be_action
      to: 'double'
  action:
    - service: light.turn_on
      entity_id: light.led_color_k
      data_template:
        brightness_pct: 100
        kelvin: 5000

# ##################################
# Kitchen Table Lamp (Yeelight E27 Color) to midnight
# ##################################
- alias: kitchen_table_lamp_to_midnight
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.switch_158d0001ef61be
    #     click_type: long_click_press
    - platform: state
      entity_id: sensor.0x158d0001ef61be_action
      to: 'hold'
  action:
    - service: light.turn_on
      entity_id: light.led_color_k
      data_template:
        brightness_pct: 5
        kelvin: 3000
      
# ##################################
# Kitchen - Timer restart with movement
# ################################## 
- alias: kitchen_timer_restart
  initial_state: 'true'
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002b4729d_motion, binary_sensor.0x158d0002b48381_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.round_led_k #switch.wall_switch_right_158d0002a36f7f
      state: 'on'
    - condition: template
      value_template: "{{(as_timestamp(now())-as_timestamp(state_attr('automation.kitchen_timer_restart','last_triggered'))|int) > 15 }}"
  action:
    # - service: timer.cancel
    #   entity_id: timer.main_light_k
    - service: timer.start
      entity_id: timer.main_light_k

# ##################################
# Kitchen - Timer off
# ################################## 
- alias: kitchen_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_k #switch.wall_switch_right_158d0002a36f7f
      to: 'off'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_k
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_light_on
    - delay: '00:00:15'
    - service: automation.turn_on
      entity_id: automation.kitchen_auto_light_on
    
    
# ##################################
# Kitchen - Timer start on light on
# ################################## 
- alias: kitchen_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_k #switch.wall_switch_right_158d0002a36f7f
      to: 'on'
  # condition:
  #   condition: time
  #   after: '07:00:00'
  #   before: '21:00:00'
  action:
    - service: automation.turn_on
      entity_id: automation.kitchen_auto_light_on
    - service: timer.cancel
      entity_id: timer.main_light_k
    - service: timer.start
      entity_id: timer.main_light_k
    - service: light.turn_off #switch.turn_off
      entity_id: light.magichome_mono_strip_light #switch.0x00158d000216528c_switch #switch.plug_158d000216528c
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_night_light
        
# ##################################
# Kitchen - Auto Light Off
# ##################################
- alias: kitchen_auto_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_k
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    #- service: switch.turn_off
    #  entity_id: switch.wall_switch_right_158d0002a36f7f
    - service: light.turn_off
      entity_id: light.round_led_k

# ##################################
# Kitchen - Auto Light On
# ##################################
- alias: kitchen_auto_light_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002b4729d_motion, binary_sensor.0x158d0002b48381_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.round_led_k
        state: 'off'
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'on'
      - condition: state
        entity_id: input_boolean.security_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.0x4cf8cdf3c77271d_illuminance
        below: 250
  action:
    - service: light.turn_on
      entity_id: light.round_led_k

# ##################################
# Kitchen - Auto Night Light
# ##################################
- alias: kitchen_auto_night_light
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002b4729d_motion, binary_sensor.0x158d0002b48381_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.magichome_mono_strip_light #switch.0x00158d000216528c_switch #switch.plug_158d000216528c
        state: 'off'
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: light.round_led_k #switch.wall_switch_right_158d0002a36f7f
        state: 'off'
      - condition: state
        entity_id: switch.0x158d0002a365df_channel_1
        state: 'off'
      - condition: state
        entity_id: switch.0x158d0002a365df_channel_2
        state: 'off'
      - condition: state
        entity_id: switch.ss5_hood_light #switch.esp32_kitchen_light
        state: 'off'
  action:
    - service: light.turn_on #switch.turn_on
      entity_id: light.magichome_mono_strip_light #switch.0x00158d000216528c_switch #switch.plug_158d000216528c
    - delay: '00:00:30'
    - service: light.turn_off #switch.turn_off
      entity_id: light.magichome_mono_strip_light #switch.0x00158d000216528c_switch #switch.plug_158d000216528c
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_night_light
      

# ##################################
# Kitchen - Work Light L
# ##################################
- alias: kitchen_work_light_l
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00023e5f2a_action
      to: 'single'
  action:
    - service: switch.toggle
      entity_id: switch.0x158d0002a365df_channel_1

# ##################################
# Kitchen - Work Light R
# ##################################
- alias: kitchen_work_light_R
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001ef609b_action
      to: 'single'
  action:
    - service: switch.toggle
      entity_id: switch.0x158d0002a365df_channel_2
    
# ##################################
# Kitchen - Hood Light
# ##################################
- alias: kitchen_hood_light
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001e0784e_action
      to: 'button_1_single'
  action:
    - service: switch.toggle
      entity_id: switch.ss5_hood_light

# ##################################
# Kitchen - Round Led K restart
# ##################################
- alias: kitchen_main_lamp_restart
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.round_led_k
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.round_led_k_restart

# ##################################
# Kitchen - Turn Lamp Switch On if Off
# ##################################
- alias: kitchen_main_lamp_switch_on_if_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002a36f7f_action
      to: 'button_2_single'
  condition:
    condition: state
    entity_id: switch.sonoff_basic_2_relay
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_basic_2_relay

# ##################################
# Kitchen Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: kitchen_main_lamp_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0002a36f7f_action
      to: 'button_2_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.round_led_k
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.round_led_k
        - conditions:
            - condition: state
              entity_id: light.round_led_k
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.round_led_k
              data_template:
                brightness_pct: 100
                kelvin: 5000

# ##################################
# Kitchen Main Lamp (Xiaomi Round LED) - On
# ##################################
# - alias: kitchen_main_lamp_set_brightness
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.round_led_k
#       to: 'on'
#       from: 'off'
#   action:
#     - service: light.turn_on
#       entity_id: light.round_led_k
#       data_template:
#         brightness_pct: 100
#         kelvin: 5000
        
# ##################################
# Kitchen Main Lamp (Xiaomi Round LED) - On
# ##################################
- alias: kitchen_main_lamp_off_auto_mode
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.round_led_k
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_k
    - service: automation.turn_off
      entity_id: automation.kitchen_auto_light_on
    - delay: '00:00:10'
    - service: automation.turn_on
      entity_id: automation.kitchen_auto_light_on