# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom - Timer restart with movement
# ################################## 
- alias: bathroom_timer_restart
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000236bc6d_motion
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
        state: 'on'
      - condition: state
        entity_id: light.mirror_light_b
        state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_b
    - service: timer.start
      entity_id: timer.main_light_b

# ##################################
# Bathroom - Timer off
# ################################## 
- alias: bathroom_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
      to: 'off'
      from: 'on'
  action:
    # - service: automation.turn_off
    #   entity_id: automation.bathroom_timer_restart
    # - service: timer.cancel
    #   entity_id: timer.main_light_b
    - service: light.turn_off
      entity_id: light.mirror_light_b
    # - service: automation.turn_on
    #   entity_id: automation.bathroom_timer_restart
    
# ##################################
# Bathroom - Timer start on light on
# ################################## 
- alias: bathroom_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: light.mirror_light_b
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: timer.main_light_b
      state: 'idle'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_b
    - service: timer.start
      entity_id: timer.main_light_b

# ##################################
# Bathroom - Timer pause on
# ################################## 
- alias: bathroom_timer_pause_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000236bc6d_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.0x158d0002a14c5e_contact
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
          state: 'on'
        - condition: state
          entity_id: light.mirror_light_b
          state: 'on'
  action:
    - service: timer.pause
      entity_id: timer.main_light_b
    - service: homeassistant.turn_off
      entity_id: automation.bathroom_timer_restart
      
# ##################################
# Bathroom - Timer pause off
# ################################## 
- alias: bathroom_timer_pause_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d0002a14c5e_contact
      from: 'off'
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
        state: 'on'
      - condition: state
        entity_id: light.mirror_light_b
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.main_light_b
    - service: homeassistant.turn_on
      entity_id: automation.bathroom_timer_restart
      
# ##################################
# Bathroom - Auto Light On
# ##################################
- alias: bathroom_auto_light_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000236bc6d_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
      state: 'off'
  action:
    # - service: light.turn_on
    #   entity_id: light.mirror_light_b
    - service: xiaomi_miio.light_set_scene
      entity_id: light.mirror_light_b
      data:
        scene: 4

# ##################################
# Bathroom - Auto Light Off
# ##################################
- alias: bathroom_auto_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_b
  action:
    - service: switch.turn_off
      entity_id: switch.0x4cf8cdf3c7a9a48_channel_2
    - service: light.turn_off
      entity_id: light.mirror_light_b

# ##################################
# Bathroom - Light Toggle with Repeater
# ##################################
- alias: bathroom_light_toggle_repeater
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001e0a622_action
      to: 'button_1_single'
  action:
    - service_template: switch.turn_{%if is_state('switch.0x4cf8cdf3c7a9a48_channel_2','on')%}off{%else%}on{%endif%} #service: switch.toggle
      entity_id: switch.0x4cf8cdf3c7a9a48_channel_2

# ##################################
# Bathroom - Mirror Light
# ##################################
- alias: bathroom_button_mirror
  initial_state: 'true'
  mode: restart
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001ef6089_action
  condition:
    - condition: template
      value_template: >-
        {{ trigger.to_state.state in ['single', 'double','release', 'hold'] }}
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001ef6089_action
              state: 'single'
          sequence:
            - service: light.toggle
              entity_id: light.mirror_light_b
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001ef6089_action
              state: 'double'
          sequence:
            - service: xiaomi_miio.light_set_scene
              entity_id: light.mirror_light_b
              data:
                scene: 1
        - conditions:
            - condition: state
              entity_id: sensor.0x158d0001ef6089_action
              state: 'hold'
          sequence:
            - service: xiaomi_miio.light_set_scene
              entity_id: light.mirror_light_b
              data:
                scene: 4

# ##################################
# Bathroom - Mirror Light Manual
# ##################################
- alias: bathroom_mirror_light_manual
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_3_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.mirror_light_b
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.mirror_light_b
        - conditions:
            - condition: state
              entity_id: light.mirror_light_b
              state: 'off'
          sequence:
            - service: xiaomi_miio.light_set_scene
              entity_id: light.mirror_light_b
              data_template:
                scene: 4

# ##################################
# Bathroom - Mirror Light Bright
# ##################################
- alias: bathroom_mirror_light_bright
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x4cf8cdf3c7a9a48_action
      to: 'button_3_double'
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.mirror_light_b
      data_template:
        scene: 1

# ##################################
# Bathroom - Mirror Light Mode
# ##################################
# - alias: bathroom_mirror_light_mode
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.mirror_light_b
#       from: 'off'
#       to: 'on'
#   action:
#     - service: xiaomi_miio.light_set_scene
#       entity_id: light.mirror_light_b
#       data_template:
#         scene: "{% if is_state('switch.0x4cf8cdf3c7a9a48_channel_2','off') %}4{%else%}1{%endif%}"

# # ##################################
# # Bathroom - Mirror light off
# # ##################################
# - alias: bathroom_mirror_light_off
#   initial_state: 'false'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.0x158d000236bc6d_motion
#       from: 'on'
#       to: 'off'
#       for: 
#         minutes: 15
#   action:
#     - service: light.turn_off
#       entity_id: light.mirror_light_b
      
# ##################################
# Bathroom - Mirror Light Reset 
# ##################################
- alias: bathroom_mirror_light_reset
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.mirror_light_b
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.mirror_light_b_restart