# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom Water Valves Test
# ##################################
- alias: bathroom_water_valves_test
  id: bathroom_water_valves_test
  initial_state: true
  triggers:
    - trigger: time
      at: "00:01:00"
  conditions:
    - "{{ now().timestamp() | timestamp_custom('%d') | int(0) == 15 }}"
  actions:
    - action: notify.send_message
      data:
        entity_id: notify.telegram_dima
        message: "\U0001f6b0 Проверка кранов - закрываем!"
    # - action: switch.turn_off
    #   entity_id: switch.0x00158d00039258de_plug
    # - action: switch.turn_on
    #   entity_id: switch.esp32_node_b_relay_1
    - action: button.press
      entity_id: button.esp32_node_b_close_valve
    - delay: "00:00:25"
    - action: switch.turn_off
      entity_id: switch.esp32_node_b_relay_1
    - delay: "00:00:05"
    - action: notify.send_message
      data:
        entity_id: notify.telegram_dima
        message: "\U0001f6b0 Проверка кранов - открываем!"
    # - action: switch.turn_on
    #   entity_id: switch.esp32_node_b_relay_2
    - action: button.press
      entity_id: button.esp32_node_b_open_valve
    - delay: "00:00:25"
    - action: switch.turn_off
      entity_id: switch.esp32_node_b_relay_2
    # - action: switch.turn_on
    #   entity_id: switch.0x00158d00039258de_plug
    - action: notify.send_message
      data:
        entity_id: notify.telegram_dima
        message: "\U00002705 Проверка кранов завершена!"
