# #####################################################################################
#
# BATHROOM
#
# #####################################################################################
# Bathroom Water Valves Test
# ##################################
- alias: bathroom_water_valves_test
  initial_state: "true"
  trigger:
    - platform: time
      at: '00:01:00'
  condition:
    - condition: template
      value_template: '{{ now().day == 15 }}'
  action:
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - закрываем!"
    - service: switch.turn_off
      entity_id: switch.0x158d00039258de_switch
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_1
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_1
    - delay: '00:00:05'
    - service: notify.telegram
      data_template: 
        message: "\U0001f6b0 Проверка кранов - открываем!"
    - service: switch.turn_on
      entity_id: switch.esp32_bathroom_node_relay_2
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.esp32_bathroom_node_relay_2
    - service: switch.turn_on
      entity_id: switch.0x158d00039258de_switch
    - service: notify.telegram
      data_template: 
        message: "\U00002705 Проверка кранов завершена!"