# #####################################################################################
#
# TOILET - Water Leak
#
# #####################################################################################
# Toilet - Water Leak Detected
# ##################################
- alias: toilet_water_leak_detected
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00023684c2_water_leak #binary_sensor.water_leak_sensor_158d00023684c2
      from: 'off'
      to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вним+ание! Обнар+ужена ут+ечка вод+ы в туал+ете! Обнар+ужена ут+ечка вод+ы в туал+ете! Вод+а перекрыв+ается!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Обнаружена утечка воды в туалете! Обнаружена утечка воды в туалете! Вода перекрывается!"
    - service: switch.turn_on
      entity_id: switch.0x00158d000366815b_switch_l1 #switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.0x00158d000366815b_switch_l1 #switch.plug_158d00020d8679
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а перекр+ыта! Устран+ите прот+ечку вод+ы в туал+ете дл+я включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: "\U000026d4 Внимание! Вода перекрыта! Устраните протечку воды в туалете для включения воды!"
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Сработал датчик протечки в туалете! Краны закрыты!"

# ##################################
# Toilet - Water Leak Off
# ##################################
- alias: toilet_water_leak_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d00023684c2_water_leak #binary_sensor.water_leak_sensor_158d00023684c2
      from: 'on'
      to: 'off'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Прот+ечка вод+ы в туал+ете устранен+а! Спас+ибо!'
    - service: notify.telegram
      data_template:
        message: "\U00002705 Протечка воды в туалете устранена!"