# #####################################################################################
#
# MASTER BEDROOM - UPS
#
# #####################################################################################
# Master Bedroom - Main power turned off
# ##################################
- alias: master_bedroom_main_power_turned_off
  id: master_bedroom_main_power_turned_off
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d0002467773_switch
      to: 'off'
      from: 'on'
  condition:
    - condition: state
      entity_id: sensor.zigbee2mqtt_bridge_state
      state: 'online'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Вторая розетка отключена! Запущен UPS (1050)"

# ##################################
# Master Bedroom - Main plug pulled out
# ##################################
- alias: master_bedroom_main_plug_pulled_out
  id: master_bedroom_main_plug_pulled_out
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.pc_mb
      below: 10
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Нагрузка во второй розетке упала! Проверь кабель!"

# ##################################
# Master Bedroom- Main power - over-power
# ##################################
- alias: master_bedroom_main_power_overpower
  id: master_bedroom_main_power_overpower
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.pc_mb
      above: 1700 
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Внимание! Перегрузка второй розетки! Отключите лишние потребители!"

# ##################################
# Master Bedroom- UPS - OB
# ##################################
- alias: master_bedroom_ups_ob
  id: master_bedroom_ups_ob
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1050_status_data
      to: 'OB'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Внимание! Запущен UPS (1050)!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "Запущен UPS (1050)"

# ##################################
# Master Bedroom- UPS - LB
# ##################################
- alias: master_bedroom_ups_lb
  id: master_bedroom_ups_lb
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1050_status_data
      to: 'LB'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Заряд батареи (1050) критический! Завершение работы j3455!"
    - service: notify.mobile_app_iphone_8_dtsymbal
      data:
        title: "Внимание!"
        message: "UPS полностью разряжен! Завершаем работу j3455!"

# ##################################
# Master Bedroom- UPS - OL
# ##################################
- alias: master_bedroom_ups_ol
  id: master_bedroom_ups_ol
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1050_status_data
      to: 'OL'
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state not in ['unknown','unavailable','none'] }}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50b Питание восстановлено! Начинаем заряд батареи(1050)!"

# ##################################
# Master Bedroom- UPS - Unknown
# ##################################
- alias: master_bedroom_ups_unknown
  id: master_bedroom_ups_unknown
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.ippon_1050_status_data
      to: 'unknown'
      for:
        minutes: 5
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state not in ['unknown','unavailable','none'] }}"
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f6a8 Внимание! Связь с UPS(1050) потеряна!"
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.ippon_1050_announce

# ##################################
# Master Bedroom- Main power turned on
# ##################################
- alias: master_bedroom_main_power_turned_on
  id: master_bedroom_main_power_turned_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.0x158d0002467773_switch
      to: 'on'
  # condition:
  #   - condition: state
  #     entity_id: sensor.zigbee2mqtt_bridge_state
  #     state: 'online'
  action:
    - service: notify.telegram
      data_template:
        message: "\U0001f50c Электроснабжение восстановлено! Начинаем зарядку UPS(1050)!"
