# #####################################################################################
#
# STORAGE
#
# #####################################################################################
# Storage - Auto Light On
# ##################################
- alias: storage_auto_light_on
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.motion
    event_data:
      entity_id: binary_sensor.motion_sensor_158d0001aea602
  action:
  - service: switch.turn_on
    entity_id: switch.wall_switch_158d000248bf53

# ##################################
# Storage - Auto Light On
# ##################################
- alias: storage_auto_light_off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001aea602
    to: 'off'
    for:
      seconds: 15
  action:
  - service: switch.turn_off
    entity_id: switch.wall_switch_158d000248bf53
  
# ##################################
# Storage - Night Off
# ##################################
- alias: storage_night_off
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00023d0b86
      click_type: single
  action:
    - service: homeassistant.turn_off
      entity_id: light.led_strip_hb, switch.plug_158d0001f5501f, switch.plug_158d000216528c, switch.wall_switch_158d000248bf53, light.gateway_light_7811dcb8cb4b