# #####################################################################################
#
# HALL SMALL  - Water Leak
#
# #####################################################################################
# Hall Small - Turn Water Off
# ##################################
- alias: hall_small_turn_water_off
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.wall_switch_left_158d00026ea94e
    - platform: state
      entity_id: sensor.0x00158d00026ea94e_click
      to: 'left'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Зап+ущена процедура выключ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: 'Внимание! Запущена процедура принудительного закрытия воды!'
    - service: switch.turn_on
      entity_id: switch.0x00158d000366815b_switch_l1 #switch.plug_158d00020d8679
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.0x00158d000366815b_switch_l1 #switch.plug_158d00020d8679
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а в+ыключена!'
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Принудительное закрытие воды!"
    - service: notify.telegram
      data_template:
        message: 'Внимание! Вода принидительно закрыта!'

# ##################################
# Hall Small - Turn Water On
# ##################################
- alias: hall_small_turn_water_on
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.wall_switch_right_158d00026ea94e
    - platform: state
      entity_id: sensor.0x00158d00026ea94e_click
      to: 'right'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.0x00158d00023684c2_water_leak #binary_sensor.water_leak_sensor_158d00023684c2
        state: 'off'
      - condition: state
        entity_id: binary_sensor.0x00158d0002373a67_water_leak #binary_sensor.water_leak_sensor_158d0002373a67
        state: 'off'
      - condition: state
        entity_id: binary_sensor.0x00158d00023297e7_water_leak #binary_sensor.water_leak_sensor_158d00023297e7
        state: 'off'      
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Зап+ущена процедура включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: 'Внимание! Запущена процедура принудительного включения воды!'
    - service: switch.turn_on
      entity_id: switch.0x00158d000366815b_switch_l2 #switch.plug_158d0001f54f90
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.0x00158d000366815b_switch_l2 #switch.plug_158d0001f54f90
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а включен+а!'
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Принудительное открытие воды!"
    - service: notify.telegram
      data_template:
        message: 'Внимание! Вода принидительно открыта!'
        
# ##################################
# Hall Small - Turn Water On_Leak detected
# ##################################
- alias: hall_small_turn_water_on_leak_detected
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.wall_switch_right_158d00026ea94e
    - platform: state
      entity_id: sensor.0x00158d00026ea94e_click
      to: 'right'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.0x00158d00023684c2_water_leak #binary_sensor.water_leak_sensor_158d00023684c2
        state: 'on'
      - condition: state
        entity_id: binary_sensor.0x00158d0002373a67_water_leak #binary_sensor.water_leak_sensor_158d0002373a67
        state: 'on'
      - condition: state
        entity_id: binary_sensor.0x00158d00023297e7_water_leak #binary_sensor.water_leak_sensor_158d00023297e7
        state: 'on'      
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Включ+ение вод+ы невозм+ожно! Прот+ечка н+е устранен+а! Дл+я принуд+ительного включ+ения вод+ы нажм+ите кл+авиши Включ+ения и Выключ+ения одноврем+енно!'
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Попытка открыть воду, протечка НЕ устранена!"
    - service: notify.telegram
      data_template:
        message: 'Внимание! Попытка открыть воду, протечка НЕ устранена!'

# ##################################
# Hall Small - Turn Water On_Force
# ##################################
- alias: hall_small_turn_water_on_force
  initial_state: 'true'
  trigger:
    # - platform: event
    #   event_type: xiaomi_aqara.click
    #   event_data:
    #     entity_id: binary_sensor.wall_switch_both_158d00026ea94e
    - platform: state
      entity_id: sensor.0x00158d00026ea94e_click
      to: 'both'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Прот+ечка вод+ы н+е устранен+а! Зап+ущена процедура принуд+ительного включ+ения вод+ы!'
    - service: notify.telegram
      data_template:
        message: 'Внимание! Протечка воды не устранена! Запущена процедура принудительного включения воды!'
    - service: switch.turn_on
      entity_id: switch.0x00158d000366815b_switch_l2 #switch.plug_158d0001f54f90
    - delay: '00:00:25'
    - service: switch.turn_off
      entity_id: switch.0x00158d000366815b_switch_l2 #switch.plug_158d0001f54f90
    - service: media_player.volume_set
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        volume_level: '{{states("input_number.main_volume")|float}}'
    - service: tts.yandextts_say
      data_template:
        entity_id: 
          - media_player.{{states('input_select.main_audio_out')|lower}}
          - media_player.home_mini_k
        message: 'Вним+ание! Вод+а включен+а! Прот+ечка н+е устранен+а!'
    - service: notify.notify
      data:
        title: "Внимание!"
        message: "Принудительное открытие воды, протечка НЕ устранена!"
    - service: notify.telegram
      data_template:
        message: 'Внимание! Принудительное открытие воды, протечка НЕ устранена!'