# #####################################################################################
#
# SASHA - Lights
#
# #####################################################################################
# Sasha Table Lamp (Philips E27)
# ##################################
- alias: sasha_table_lamp_on_if_lamp_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001f3627d_action
      to: 'single'
    - platform: state
      entity_id: sensor.0x158d0003fa6077_action
      to: 'button_2_single'
  action:
    - service: light.toggle
      entity_id: light.philips_e27_s
      # data_template:
      #   transition: 1
      #   brightness_pct: >
      #     {%- if is_state('binary_sensor.tod_day','off') -%}
      #     3
      #     {%- else -%}
      #     100
      #     {% endif %}
      #   kelvin: >
      #     {%- if is_state('binary_sensor.tod_day','off') -%}
      #     3000
      #     {%- else -%}
      #     5000
      #     {% endif %}

# ##################################
# Sasha - Main Lamp (Xiaomi Round LED)
# ##################################
- alias: sasha_main_lamp
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0003fa6077_action
      to: 'button_1_single'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.square_led_s
        - conditions:
            - condition: state
              entity_id: light.square_led_s
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.square_led_s
              data_template:
                brightness_pct: 100
                kelvin: 5000

# ##################################
# Sasha Table Lamp (Philips E27) - Switch to Bright
# ##################################
- alias: sasha_table_lamp_bright
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001f3627d_action
      to: 'double'
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
        scene: 1
    # - service: light.turn_on
    #   entity_id: light.0x00124b000a9e26af_light
    #   data_template:
    #     transition: 1
    #     brightness_pct: 100
    #     kelvin: 5000

# ##################################
# Sasha Table Lamp (Philips E27) - Switch to Mid-Night
# ##################################
- alias: sasha_table_lamp_night
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0001f3627d_action
      to: 'hold'
  action:
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
        scene: 4
    # - service: light.turn_on
    #   entity_id: light.0x00124b000a9e26af_light
    #   data_template:
    #     transition: 1
    #     brightness_pct: 3
    #     kelvin: 3000

# ##################################
# Sasha - Table Lamp Off (scene4) when main turned on
# ################################## 
- alias: sasha_table_lamp_off_night_mode_main_on
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/3"
  condition:
    - condition: template
      value_template: "{{state_attr('light.philips_e27_s','scene')|int == 4}}"
    - condition: state
      entity_id: light.square_led_s
      state: 'on'
    - condition: state
      entity_id: light.philips_e27_s
      state: 'on'
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.philips_e27_s

# ##################################
# Sasha - Auto Night Light
# ##################################
- alias: sasha_auto_nightlight_on
  initial_state: 'false'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000224f89f_motion, binary_sensor.0x00158d000224f89f_occupancy
      #from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: 'off'
      - condition: state
        entity_id: person.sasha
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.philips_e27_s
    - service: xiaomi_miio.light_set_scene
      entity_id: light.philips_e27_s
      data:
          scene: 4

# ##################################
# Sasha - Auto Night Light Off 30m without movements
# ##################################
- alias: sasha_night_auto_off_30m
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_s
      from: 'on'
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.philips_e27_s

# ##################################
# Sasha - Auto Night Light Off in the morning
# ##################################
# - alias: sasha_night_auto_off_morning
#   initial_state: 'true'
#   trigger:
#     - platform: time_pattern
#       minutes: '/1'
#   condition:
#     # - condition: template
#     #   value_template: "{{state_attr('light.philips_e27_s','scene')|int == 4}}"
#     # - condition: state
#     #   entity_id: light.philips_e27_s
#     #   state: 'on'
#     - condition: numeric_state
#       entity_id: sensor.0x04cf8cdf3c77271d_illuminance_lux
#       above: 500
#     - condition: template
#       value_template: "{{ state_attr('light.0x00124b000a9e26af_light','brightness')|int < 10 }}" #"{{state_attr('light.philips_e27_s','scene')|int == 4}}"
#     - condition: state
#       entity_id: light.philips_e27_s
#       state: 'on'
#   action:
#     - service: light.turn_off
#       entity_id: light.philips_e27_s

# ##################################
# Sasha - Round LED Reset 
# ##################################
- alias: sasha_round_led_reset
  initial_state: 'true'
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: light.square_led_s
      state: 'unavailable'
      for:
        minutes: 2
  action:
    - service: script.turn_on
      entity_id: script.square_led_s_restart

# ##################################
# Sasha - Turn Lamp Switch On if Off
# ##################################
- alias: sasha_main_lamp_switch_on_if_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d0003fa6077_action
      to: 'button_1_single'
    - platform: state
      entity_id: sensor.0x158d0003fa6077_action
      to: 'button_2_single'
  condition:
    condition: state
    entity_id: switch.sonoff_basic_1_relay
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_basic_1_relay

# ##################################
# Sasha - Timer restart with movement
# ################################## 
- alias: sasha_timer_restart
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.0x158d000224f89f_motion, binary_sensor.0x158d0003140824_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: light.square_led_s
      state: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# ##################################
# Sasha - Timer off
# ################################## 
- alias: sasha_timer_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.square_led_s
      to: 'off'
      from: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.main_light_s
#    - service: automation.turn_off
#      entity_id: automation.sasha_auto_light_on
#    - delay: '00:00:10'
#    - service: automation.turn_on
#      entity_id: automation.sasha_auto_light_on
    
# ##################################
# Sasha - Timer start on light on
# ################################## 
- alias: sasha_timer_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: light.square_led_s
      to: 'on'
      from: 'off'
  action:
    #- service: automation.turn_on
    #  entity_id: automation.sasha_auto_light_on
    - service: timer.cancel
      entity_id: timer.main_light_s
    - service: timer.start
      entity_id: timer.main_light_s

# ##################################
# Sasha - Auto Light Off
# ##################################
- alias: sasha_auto_light_off
  initial_state: 'true'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.main_light_s
  condition:
    - condition: state
      entity_id: binary_sensor.tod_day
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.square_led_s

# ##################################
# Sasha - Auto Light On
# ##################################
# - alias: sasha_auto_light_on
#   initial_state: 'true'
#   trigger:
#     - platform: event
#       event_type: xiaomi_aqara.motion
#       event_data:
#         entity_id: binary_sensor.motion_sensor_158d000224f89f
#   condition:
#     condition: and
#     conditions:
#       - condition: state
#         entity_id: light.square_led_s
#         state: 'off'
#       - condition: state
#         entity_id: binary_sensor.tod_day
#         state: 'on'
#       - condition: state
#         entity_id: sun.sun
#         state: below_horizon
#   action:
#     - service: light.turn_on
#       entity_id: light.square_led_s
      
# ##################################
# Sasha - Auto Ambilight On
# ##################################
# - alias: sasha_auto_ambilight_light
#   initial_state: 'true'
#   trigger:
#     - platform: state
#       entity_id: light.square_led_s
#   action:
#     - service: script.turn_on
#       data_template:
#         entity_id: script.sasha_ambilight_{{ states('light.square_led_s') | lower }}

# ##################################
# Sasha - LED Strip Control with round key
# ##################################
- alias: sasha_led_strip_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00019c8afd_action
      to: 'single'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.d1mini_co2_s_led
        effect: '{{ (["Random", "Rainbow", "Color Wipe", "Scan", "Twinkle", "Random Twinkle"] | random) }}'

# ##################################
# Sasha - LED Strip Control Color Swipe with round key
# ##################################
- alias: sasha_led_strip_on
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00019c8afd_action
      to: 'double'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.d1mini_co2_s_led
        effect: 'Color Wipe'
        
# ##################################
# Sasha - LED Strip Control off with round key
# ##################################
- alias: sasha_led_strip_off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: sensor.0x158d00019c8afd_action
      to: 'hold'
  action:
    - service: light.turn_off
      entity_id: light.d1mini_co2_s_led