substitutions:
  board_name: bk7231n_strip_dima_v
  node_name: bk7231n-strip-dima-v
  
esphome:
  name: ${node_name}
  comment: LED Bed Dima V

bk72xx:
  board: generic-bk7231n-qfn32-tuya

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pass
  domain: !secret my_domain
  reboot_timeout: 15min
  #use_address: 192.168.200.76
  #fast_connect: true
  #output_power: 17.5dB
  #power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.1.98
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8

safe_mode:
  disabled: False
  num_attempts: 5
  reboot_timeout: 15min

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:
  port: 80

binary_sensor:
  - platform: status
    name: "Status"

text_sensor:
  - platform: template
    name: "Uptime"
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
    mac_address:
      name: "MAC"
    # scan_results:
    #   name: "Latest Scan Results"

  - platform: libretiny
    version:
      name: ${board_name}_LibreTiny Version
      
sensor:
  - platform: uptime
    name: "Uptime s"
    id: uptime_sensor
    update_interval: 15s
    disabled_by_default: true
    
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s

button:
  - platform: restart
    name: "Restart"
    id: id_restart_button

output:
  - platform: libretiny_pwm
    id: output_light
    pin: P7

light:
  - platform: monochromatic
    name: "LED"
    output: output_light


time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow