substitutions:
  board_name: esp32_node_st
  node_name: esp32-node-st
  up_int: 60s
  
esphome:
  name: ${node_name}
  comment: ESP32 Node St
  # platformio_options:
  #   board_build.partitions: ../../../custom_components/partitions_esp32_4mb.csv

safe_mode:
  disabled: False
  num_attempts: 5
  reboot_timeout: 15min

# external_components:
#   - source:
#       type: git
#       url: https://github.com/ssieb/esphome
#       ref: onewire
#     components: [ gpio ]
#     refresh: 1min

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pass
  domain: !secret my_domain
  reboot_timeout: 15min
  #output_power: 17.5dB
  #fast_connect: true
  #use_address: 192.168.1.246
  #power_save_mode: none
  # manual_ip:
  #   static_ip: 192.168.1.109
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8

logger:
  baud_rate: 0

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

one_wire:
  - platform: gpio
    pin: GPIO13
    id: bus12
  - platform: gpio
    pin: GPIO16
    id: bus34

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: uptime
    name: "Uptime s"
    id: uptime_sensor
    update_interval: 15s
    disabled_by_default: true
    
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s

  - platform: dallas_temp
    address: 0x5e3ce104570ba028
    name: ${board_name}_dallas_1
    one_wire_id: bus12
    # accuracy_decimals: 2
    # resolution: 12

  - platform: dallas_temp
    address: 0xb63ce10457eb0228
    name: ${board_name}_dallas_2
    one_wire_id: bus12
    # accuracy_decimals: 2
    # resolution: 12

  - platform: dallas_temp
    address: 0xfb3ce10457006d28
    name: ${board_name}_dallas_3
    one_wire_id: bus34
    # accuracy_decimals: 2
    # resolution: 12

  - platform: dallas_temp
    address: 0xcf3ce10457ded728
    name: ${board_name}_dallas_4
    one_wire_id: bus34
    # accuracy_decimals: 2
    # resolution: 12

text_sensor:
  - platform: template
    name: "Uptime"
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
    mac_address:
      name: "MAC"
    # scan_results:
    #   name: "Latest Scan Results"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    
button:
  - platform: restart
    name: "Restart"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow