substitutions:
  node_name: esp32-bsh-washer
  friendly_name: "ESP32 Washer B"

  rx_pin: GPIO4

esphome:
  name: ${node_name}
  friendly_name: ${friendly_name}
  comment: "BSH Washer monitor (Bosch WAS28743 / Logixx 8, EPW66018 mainboard)"
  area: "Bathroom"
  on_boot:
    priority: 800
    then:
      - ble.disable:
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

esp32_ble:
  enable_on_boot: False
    
safe_mode:
  disabled: False
  num_attempts: 5
  reboot_timeout: 15min

preferences:
  flash_write_interval: 10min

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pass
  domain: !secret my_domain
  reboot_timeout: 15min
  min_auth_mode: WPA2
  power_save_mode: none

logger:
  baud_rate: 0 # UART is used by the washing machine D-Bus, log only via WiFi/USB

api:

ota:
  - id: esphome_ota
    platform: esphome

uart:
  - id: dbus_uart
    rx_pin: ${rx_pin}
    baud_rate: 9600
    rx_buffer_size: 1024

external_components:
  - source:
      type: local
      path: custom_components/bsh-home-appliances
    components: [bshdbus]

bshdbus:
  uart_id: dbus_uart
  on_frame:
    - logger.log:
        format: "Received frame dest 0x%02x cmd 0x%04x: 0x%s"
        args: [dest, command, format_hex(message).c_str()]

binary_sensor:
  - platform: status
    name: "Status"
    
  - platform: bshdbus
    dest: 0x14
    command: 0x1007
    binary_sensors:
      - id: bsh_wm_feat_waterplus
        name: "Water Plus"
        icon: mdi:water-plus
        lambda: return (x[0] >> 1) & 0x01;
      - id: bsh_wm_feat_speedplus
        name: "Speed Perfect"
        icon: mdi:clock-fast
        lambda: |-
          int sensor_value = x[0];
            int mask = 0b01100000; // Mask for bits in positions 6 and 7
            if ((sensor_value & mask) == 0) {
                // The bits in positions 6 and 7 are at zero
                return 1;
            } else {
                // At least one of the bits is set to 1
                return 0;
            }
      - id: bsh_wm_feat_stains
        name: "Eco Perfect"
        icon: mdi:leaf
        lambda: return (x[0] >> 5) & 0x01;
      - id: bsh_wm_feat_prewash
        name: "Pre-wash"
        icon: mdi:rotate-orbit
        lambda: return (x[0] >> 7) & 0x01;
      - id: bsh_wm_feat_anticrease
        name: "Anti-crease"
        icon: mdi:iron
        lambda: return (x[1] >> 7) & 0x01;
  - platform: bshdbus
    dest: 0x14
    command: 0x1008
    binary_sensors:
      - id: bsh_wm_feat_nospin
        name: "No Spin"
        icon: mdi:rotate-3d-variant
        lambda: return x[0] & 0x01;
  - platform: bshdbus
    dest: 0x15
    command: 0x1100
    binary_sensors:
      - id: bsh_wm_start_button
        name: "Start Button"
        icon: mdi:button-pointer
        lambda: return 1;
        on_press:
          - delay: 1s
          - lambda: id(bsh_wm_start_button).publish_state(NAN);
  - platform: bshdbus
    dest: 0x26
    command: 0x1701
    binary_sensors:
      - id: bsh_wm_program_started
        name: "Wash Program Started"
        entity_category: diagnostic
        icon: mdi:ray-start-arrow
        lambda: return 1;
        on_press:
          - delay: 1s
          - lambda: id(bsh_wm_program_started).publish_state(NAN);

sensor:
  - platform: bshdbus
    dest: 0x14
    command: 0x1006
    sensors:
      - id: bsh_wm_rpm
        name: "Spin Speed"
        device_class: speed
        state_class: measurement
        unit_of_measurement: rpm
        accuracy_decimals: 0
        lambda: return x[0];
        filters:
          - multiply: 10
          - lambda: |
              if (x > 1300) return 1400; //the 'marketing' max speed is higher than what the machine is actual capable of
              else return x;

  - platform: bshdbus
    dest: 0x16
    command: 0x3015
    sensors:
      - id: bsh_wm_rpm_ontime
        name: "Drum Speed (current)"
        entity_category: diagnostic
        accuracy_decimals: 0
        device_class: speed
        unit_of_measurement: rpm
        lambda: return (((int16_t) x[3] << 8 | x[4])/16);
    #  - id: bsh_wm_rpm_median
    #    name: Drum Speed (averaged)
    #    entity_category: diagnostic
    #    accuracy_decimals: 0
    #    device_class: speed
    #    unit_of_measurement: rpm
    #    lambda: return (((int16_t) x[6] << 8 | x[7])/16);

  - platform: bshdbus
    dest: 0x17
    command: 0x4010
    sensors:
      - id: bsh_wm_unbalance_x
        name: "Imbalance X"
        entity_category: diagnostic
        icon: mdi:axis-x-rotate-clockwise
        accuracy_decimals: 0
        lambda: return (int16_t) ((x[1] << 8) | x[2]);
        filters:
          - throttle: 30s
          - timeout: 90s
      - id: bsh_wm_unbalance_z
        name: "Imbalance Z"
        entity_category: diagnostic
        icon: mdi:axis-z-rotate-clockwise
        accuracy_decimals: 0
        lambda: return (int16_t) ((x[3] << 8) | x[4]);
        filters:
          - throttle: 30s
          - timeout: 90s
      - id: bsh_wm_unbalance_y
        name: "Imbalance Y"
        entity_category: diagnostic
        icon: mdi:axis-y-rotate-clockwise
        accuracy_decimals: 0
        lambda: return (int16_t) ((x[5] << 8) | x[6]);
        filters:
          - throttle: 30s
          - timeout: 90s
  - platform: bshdbus
    dest: 0x2a
    command: 0x1600
    sensors:
      - id: bsh_wm_remain
        name: "Remaining Time"
        device_class: duration
        state_class: measurement
        unit_of_measurement: min
        accuracy_decimals: 0
        lambda: return x[0];
  - platform: bshdbus
    dest: 0x14
    command: 0x1004
    sensors:
      - id: bsh_wm_temperature
        name: "Temperature"
        icon: mdi:thermometer
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C
        accuracy_decimals: 0
        lambda: return x[0];
        filters:
          - calibrate_linear:
              method: exact
              datapoints:
                - 0 -> 0.0
                - 1 -> 20.0
                - 2 -> 30.0
                - 3 -> 40.0
                - 4 -> 60.0
                - 5 -> 70.0
                - 6 -> 80.0
                - 7 -> 90.0
  - platform: bshdbus
    dest: 0x14
    command: 0x1007
    sensors:
      - id: bsh_wm_extra_rinse
        name: "Extra Rinse"
        icon: mdi:water-plus-outline
        accuracy_decimals: 0
        lambda: |-
          return ((x[0] >> 4) & 0x01) + ((x[0] >> 3) & 0x01) + ((x[0] >> 2) & 0x01);

  - platform: uptime
    name: "Uptime s"
    id: uptime_sensor
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s

text_sensor:
  - platform: bshdbus
    dest: 0x14
    command: 0x1005
    text_sensors:
      - id: bsh_wm_program
        name: "Wash Program"
        icon: mdi:numeric
        lambda: return std::to_string(x[2]);
        filters:
          - map:
            - 0 -> Off
            - 1 -> Cottons
            - 2 -> Synthetics
            - 3 -> Quick/Mixed
            - 4 -> Delicates/Silk
            - 5 -> Wool
            - 6 -> Rinse
            - 7 -> Spin
            - 8 -> Drain
            - 9 -> Delicate Spin
            - 10 -> Super Quick
            - 11 -> Kids Clothing
            - 12 -> Sportswear
            - 13 -> Shirts/Blouses
            - 14 -> Down/Duvets
            - 15 -> My Program
  - platform: bshdbus
    dest: 0x16
    command: 0x3015
    text_sensors:
      - id: bsh_wm_curr_rotdirection
        name: "Current Rotation Direction"
        entity_category: diagnostic
        icon: mdi:crop-rotate
        lambda: return std::to_string(x[2]);
        filters:
          - map:
            - 108 -> Clockwise
            - 114 -> Counter-clockwise
  - platform: bshdbus
    dest: 0x26
    command: 0x1200
    text_sensors:
      - id: bsh_wm_door
        name: "Door"
        icon: mdi:door
        lambda: return std::to_string(x[0]);
        filters:
          - map:
            - 0 -> Closed, unlocked
            - 1 -> Closed, locked
            - 2 -> Open
  - platform: bshdbus
    dest: 0x26
    command: 0x1020
    text_sensors:
      - id: bsh_wm_washmodule
        name: "Program Step"
        entity_category: diagnostic
        icon: mdi:map-marker-path
        lambda: return std::to_string(x[0]);
        filters:
          - map:
            - 3 -> Dispensing detergent (3)
            - 4 -> Filling water (4)
            - 5 -> Heating (5)
            - 6 -> Agitation (6)
            - 9 -> Draining / Spinning (9)
            - 13 -> Rinsing (13)
            - 15 -> Draining / Spinning (15)
            - 16 -> Rinsing (16)
            - 20 -> Draining / Spinning (20)
            - 23 -> Rinsing (23)
            - 26 -> Final spin (26)
            - 28 -> Fluffing (28)
  - platform: bshdbus
    dest: 0x26
    command: 0x1101
    text_sensors:
      - id: bsh_wm_state
        name: "Status"
        icon: mdi:state-machine
        lambda: return std::to_string(x[0]);
        filters:
        - map:
          - 0 -> Stopped/Ready
          - 1 -> Finished
          - 2 -> Running

  - platform: template
    name: "Uptime"
    lambda: |-
        int seconds = round(id(uptime_sensor).get_raw_state());
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 60s

  - platform: wifi_info
    ip_address:
      name: "IP"
    ssid:
      name: "SSID"
    bssid:
      name: "BSSID"
    mac_address:
      name: "MAC"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

button:
  - platform: restart
    name: "Restart"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Moscow
