substitutions:
  board_name: esp32_m5_camera_hb
  node_name: esp32-m5-camera-hb
 
esphome:
  name: ${node_name}

esp32:
  board: esp32cam
  
wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_pass
  domain: !secret my_domain
  # fast_connect: true
  reboot_timeout: 15min
  # manual_ip:
  #   static_ip: 192.168.1.188
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  #   dns1: 192.168.1.1
  #   dns2: 8.8.8.8

logger:
  baud_rate: 0
  
api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:
  port: 80

esp32_camera:
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15

  name: ${board_name}_Camera
  resolution: 2048x1536
  jpeg_quality: 10
  max_framerate: 20fps
  idle_framerate: 1fps
  vertical_flip: true
  horizontal_mirror: false

output:
  - platform: gpio
    pin: GPIO2
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: ${board_name}_Light

binary_sensor:
  - platform: status
    name: ${board_name}_Status

  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    name: ${board_name}_Button

sensor:    
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s
    
  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s

  - platform: adc
    pin: GPIO38
    name: ${board_name}_Battery_Voltage
    filters:
      - multiply: 3.3
  
text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    # scan_results:
    #   name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

button:
  - platform: restart
    name: ${board_name}_Restart
  
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3
